### ISSUE TITLE
동아리 소개글이 길 경우 생략해서 출력해주는 기능

### ISSUE THREAD

**Issue by cyh6327** [cyh6327/ycc_club#18]

**Comment by cyh6327** [comment]
## text-overflow 속성 사용(css)
#### text-overflow 의 조건 
1. width 또는 height가 고정적일 것
2. overflow: hidden; 을 사용해 영역을 감출 것
3. 아래줄로 내려가는 것을 막기위해 white-space: nowrap 등이 필요
4. 부모 요소의 display 속성이 block이여야 한다. 
text-overflow 속성은 블럭형태인 경우에만 적용되기 때문
```css
.txt { 		
      overflow: hidden;  		// 을 사용해 영역을 감출 것
      text-overflow: ellipsis;  	// 로 ... 을 만들기 
      white-space: nowrap; 	// 아래줄로 내려가는 것을 막기위해	
      width: 300px;
      height: 20px;
}
```
